services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - CUDA_VISIBLE_DEVICES=""
      - FLASK_APP=flaskAPI.py
      - FLASK_ENV=development