services:
  jupyter:
    deploy:
        resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
    build:
      context: .
      dockerfile: jupyter.Dockerfile
      target: jupyter
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - D:/RAG Research/Code/Preprocessing/PDF/Detectron2_container:/tf
    command: ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/tf --ip 0.0.0.0 --no-browser --allow-root"]
